version: "2"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "pickup"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"

volumes:
  db-data:
    driver: local
